// NLWeb endpoint for Sipiteno (Microsoft Copilot / Bing Chat)
// Auto-generated by growth engine

const content = [
  {
    "@type": "Question",
    "name": "What does a SaaS growth consultant do?",
    "acceptedAnswer": "A SaaS growth consultant analyzes your funnel, identifies the highest-ROI growth levers, and creates an execution plan covering SEO, content, conversion, and paid channels.",
    "url": "https://sipiteno.com/#faq"
  },
  {
    "@type": "Question",
    "name": "How long until I see growth results?",
    "acceptedAnswer": "Most SaaS companies see initial results in 4-8 weeks. SEO and content compound over 3-6 months. Paid channels work immediately but require optimization.",
    "url": "https://sipiteno.com/#faq"
  },
  {
    "@type": "Question",
    "name": "What's the fastest way to get SaaS users?",
    "acceptedAnswer": "The fastest channels are typically programmatic SEO, community building (Reddit, HN, Product Hunt), and partnerships. Paid ads work if your CAC < LTV.",
    "url": "https://sipiteno.com/#faq"
  }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  
  const query = req.method === 'POST' 
    ? (req.body?.query || '').toLowerCase()
    : (req.query.query || '').toLowerCase();
  
  // Search FAQs
  const matches = query 
    ? content.filter(c => 
        c.name.toLowerCase().includes(query) || 
        c.acceptedAnswer.toLowerCase().includes(query)
      )
    : content;
  
  return res.json({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    'name': 'Sipiteno Knowledge Base',
    'description': 'Growth consulting for SaaS founders. Data-driven strategies for organic traffic, conversion optimization, and scaling from 0 to 10K users.',
    'numberOfItems': matches.length,
    'itemListElement': matches
  });
}
